### ISSUE TITLE
Header search path

### ISSUE THREAD

**Issue by hyl** [jordanbyron/react-native-quick-actions#1]
Hi! Just a quick note to say that I had an issue with RTCBridge.h not being found, and the solution was to change the header paths from:
`HEADER_SEARCH_PATHS = "$(SRCROOT)/../node_modules/react-native/React/**";`

to: 
`HEADER_SEARCH_PATHS = "$(SRCROOT)/../../react-native/React/**";`

in order to get this to work on my machine. Think Xcode is interpreting $(SRCROOT) as `node_modules/react-native-quick-actions/RNQuickAction`. Haven't submitted a PR as I'm not sure if this is just an issue with the way my project was configured, but figured you'd appreciate the heads up. Thanks for making this!

**Comment by jordanbyron** [comment]
Strange. It's working for me on one of my projects, but I'm willing to bet that could have something to do with my existing setup. Rather than replace the existing search path can you send a PR with the additional working search path included? I think that should cover both bases and still work. 

Thanks for checking out the project! :bowtie:

**Comment by hyl** [comment]
Fantastic, will do that then. Cheers!
