### ISSUE TITLE
[Android] Not receiving events nor inital params

### ISSUE THREAD

**Issue by JackThomson2** [jordanbyron/react-native-quick-actions#52]
iOS is working perfectly for me, so thanks for that 👍 
On Android, I'm not getting any of the launch parameters from hot or cold. I believe this could be due to that I'm using Wix's Native Navigator, any ideas?

Thanks Jack

**Comment by jordanbyron** [comment]
Hey @JackThomson2,

Glad to hear your iOS implementation is working. As for Android, it sounds like this is either a problem with your specific implementation or some conflict with Native Navigator. Since I don't have any additional details about either of those, and my guess is it isn't actually a problem with react-native-quick-actions, you're probably best off posting to stackoverflow to see if anyone there can help you.

This issue tracker is for bugs specifically with the react-native-quick-actions (rnqa) library. If in your travels you realize there actually is a problem specifically with rnqa, create a ticket and I'll take a look. Good luck!
