### ISSUE TITLE
Installation issue: 'RNQuickActionManager.h' file not found

### ISSUE THREAD

**Issue by 404sand808s** [jordanbyron/react-native-quick-actions#60]
Hey, feel like this should be straightforward enough but I actually can't tell what I'm doing wrong.

Followed the installation instructions as per the RN page you linked but I keep getting the error 'RNQuickActionManager.h' file not found in my import of #import "RNQuickActionManager.h" in my AppDelegate.m file. 

I did the manual install on iOS. Thanks in advance for any help or insight!

**Comment by jordanbyron** [comment]
Hey @404sand808s,

My guess is you need to make sure you follow the instructions [here](http://facebook.github.io/react-native/docs/linking-libraries-ios.html#content) which including a step to link your project to react-native-quick-actions. Hopefully that helps. If not give Stack Overflow a try and if you find a bug with our code or documentation open up a ticket here and we'll fix it.

**Comment by leonid-shevtsov** [comment]
Had the same issue. However I linked the library manually to avoid Cocoapods - then I needed to reference the header file by adding this to "Header Search Paths" (go to your project's file, select "Build Settings" and search for "Header Search Paths")

```
$(SRCROOT)/../node_modules/react-native-quick-actions/RNQuickAction/RNQuickAction
```

**Comment by Paul-Lategan** [comment]
I seem to be running into the same issue ("RNQuickActionManager.h" file not found), although I'm using Cocoapods.   

Unfortunately @leonid-shevtsov's solution did not work for me.   After adding the header search path Leonid specified, the "RNQuickActionManager.h file not found" error goes away, but I get a new error "Undefined symbol: _OBJC_CLASS_$_RNQuickActionManager". 
<img width="899" alt="Screen Shot 2020-07-07 at 11 12 41" src="https://user-images.githubusercontent.com/5661352/86683897-5e901a00-c045-11ea-8f85-4ecb8240d56e.png">
<img width="462" alt="Screen Shot 2020-07-07 at 11 15 57" src="https://user-images.githubusercontent.com/5661352/86683908-60f27400-c045-11ea-8685-84ce7d9ebf16.png">

Has anyone successfully installed this module using Cocoapods?  Sorry if I'm missing something obvious.  I don't see any mention of Cocoapods in the documentation.  Usually React Native module install guides have sections like "do this if cocoapods..  do this otherwise", so I'm unsure if following the install instructions is even relevant/supported in my case.  Can the installation instructions still work when modifying AppDelegate.m within the .xcworkspace project (not .xcodproject)?  

**Environment**
React-Native-CLI 2.0.1
React-Native 0.61.2

I've tried the following install steps:

Approach A:
1. npm install --save react-native-quick-actions
2. react-native link react-native-quick-actions
3. Open .xcworkspace and update AppDelegate.m with the code specified in the install instructions.
4. Attempt to run
5. Build fails with error (not found)
6. Modify Header Search Paths to include Leonid's solution
7. Quit XCode, restart XCode, clean build folder and click "Run"
8. Build fails with error (Undefined symbol)

Approach B:
1. react-native unlink react-native-quick-actions
2. manually link via steps 1, 2, and 3 here: https://reactnative.dev/docs/linking-libraries-ios
3. Open .xcworkspace and update AppDelegate.m with the code specified in the install instructions.
4. Modify Header Search Paths to include Leonid's solution
5. Attempt to run
6. Build fails with error (Undefined Symbol)

**Comment by Paul-Lategan** [comment]
I managed to fix this for Cocoapods by doing the following:

1. Unlink/undo any installation steps you've already tried besides npm install --save react-native-quick-actions.
2. Edit your podfile to include the following line:
`  pod 'RNQuickAction', :podspec => '../node_modules/react-native-quick-actions/RNQuickAction.podspec'`
3. Do cd ios, pod install
