### ISSUE TITLE
Add support for dynamic actions

### ISSUE THREAD

**Issue by jordanbyron** [jordanbyron/react-native-quick-actions#7]

**Comment by grabbou** [comment]
What specifically? Defining them? I have Objective-C code that does exactly that particular thing, so can submit PR over the weekend.

**Comment by jordanbyron** [comment]
@grabbou yup defining them, preferably via javascript if possible :godmode:

**Comment by grabbou** [comment]
Oh yeah, we just need to figure out the best way to support all properties, including icons (available constants and custom ones from assets) - preferred use of `require(image!...)` as much as possible. I think we can leave the `localisedTitle` and `localisedDescription` since in most cases, translation will be done on JS side with e.g. `intl`

**Comment by grabbou** [comment]
Done.

**Comment by jordanbyron** [comment]
Closed by #9
