### ISSUE TITLE
Some information for android

### ISSUE THREAD

**Issue by Angelk90** [jordanbyron/react-native-quick-actions#71]
Hi @jordanbyron, @grabbou  congratulations on the module.

I asked myself some questions:
1) It would be possible to improve the documentation related to android in particular how the various props work and put some images, a gif would be better.

I am not clear well what serveno:
`type: "Orders",` What values can you take?

`subtitle: "See orders you've made",` Where is it used in android?

`icon: "Compose",` Can I put an image taken from http?

`userInfo: {url: "app: // orders", }` What values can you take? Can there be other parameters? Can I open external app intent I have a browser web page?

2) When I put the shortcuts in the home screen, I take it the drag you can do, you create a new link in the home.
But then if I click, the same app opens, but the shortcuts home link just created is deleted.
is it a normal thing to have?

**Comment by jordanbyron** [comment]
Hey @Angelk90,

Most of your questions in #1 are covered in the readme. I don't believe Android supports the subtitle attribute at the moment so that can be ignored. Icons are described, and `userInfo` can be any custom key / value structure.

#2 sounds like a better question for stack overflow as it is asking how to use the library, not reporting a deficiency or bug, which is what this space is for. Best of luck!
